site_name: Polkadot Wiki
site_author: 'Web3 Foundation'

nav:
 - Home: index.md
 - Builders: 
   - Home: polkadot/builders/index.md
   - Building on Polkadot: polkadot/builders/build-w-polkadot.md
   - Tools: polkadot/builders/tools/index.md
   - Examples: polkadot/builders/examples/index.md
   - Networks: polkadot/builders/networks.md
 - Information:
   - FAQ: polkadot/information/faq.md
   - Roadmap: polkadot/information/polkadot_roadmap.md
   - Terms: polkadot/information/terms_and_definitions.md
 - Network Maintainer: 
   - Home: polkadot/network_maintainers/index.md
   - Node Operator / Validator: polkadot/network_maintainers/node_operator.md
   - Nominator: polkadot/network_maintainers/nominator.md
   - Collator: polkadot/network_maintainers/collator.md
   - Governance: polkadot/network_maintainers/governance/index.md
 - Chinese Polkadot Resources 中文波卡資源: other_languages/chinese.md

theme:
  custom_dir: cinder/
  name: mkdocs

favicon: favicon.ico

# theme:
#  name: 'material'
#  palette:
#    primary: 'deep orange'
#    accent: 'deep orange'
#  logo: 'images/logo.svg'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/polkadot-io'
    - type: 'twitter'
      link: 'https://twitter.com/polkadotnetwork'
    - type: 'medium'
      link: 'https://medium.com/@polkadotnetwork'

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - mathjax-config.js

# markdown_extensions:
#    - mdx_math
