site_name: Polkadot Wiki
site_author: 'Web3 Foundation'

nav:
 - Home: index.md
 - Build:
   - Home: polkadot/build/index.md
   - Building on Polkadot: polkadot/build/build_with_polkadot.md
   - Tools: polkadot/build/tools/index.md
   - Examples: polkadot/build/examples/index.md
   - Networks: polkadot/build/networks.md
 - Learn:
   - Comparisons: polkadot/learn/comparisons.md
   - Cryptography: polkadot/learn/cryptography.md
   - FAQ: polkadot/learn/faq.md
   - GRANDPA: polkadot/learn/grandpa.md
   - Roadmap: polkadot/learn/polkadot_roadmap.md
   - Terms: polkadot/learn/terms_and_definitions.md
   - Relevant Links: polkadot/learn/relevant_links.md
 - Run the Network:
   - Home: polkadot/node/index.md
   - Node Operator / Validator: polkadot/node/node_operator.md
   - Nominator: polkadot/node/nominator.md
   - Collator: polkadot/node/collator.md
   - Governance: polkadot/node/governance/index.md
 - Chinese 中文波卡資源: other_languages/chinese.md

theme:
  custom_dir: cinder/
  name: mkdocs

favicon: favicon.ico

# theme:
#  name: 'material'
#  palette:
#    primary: 'deep orange'
#    accent: 'deep orange'
#  logo: 'images/logo.svg'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/polkadot-io'
    - type: 'twitter'
      link: 'https://twitter.com/polkadotnetwork'
    - type: 'medium'
      link: 'https://medium.com/@polkadotnetwork'

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - mathjax-config.js

# markdown_extensions:
#    - mdx_math
